# Generated by Django 6.0.4 on 2026-04-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('internal', 'Internal Note')], max_length=20)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('portal', 'Portal'), ('internal', 'Internal')], default='portal', max_length=20)),
                ('sender_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes are never sent to the customer via WhatsApp')),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='Twilio Message SID — used for deduplication', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
