# Generated by Django 6.0.4 on 2026-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('internal', 'Internal Note'), ('system', 'System Event')], max_length=20),
        ),
    ]
